# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masthead_image', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('template_path', models.CharField(blank=True, default='', max_length=255)),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
