# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(default=b''),
        ),
    ]
