# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20160224_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='careergoal',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='resume.ResumeCategory'),
        ),
        migrations.AddField(
            model_name='education',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='resume.ResumeCategory'),
        ),
        migrations.AddField(
            model_name='programmingskills',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='resume.ResumeCategory'),
        ),
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='resume.ResumeCategory'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='resume.ResumeCategory'),
        ),
    ]
