# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20160228_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='career_goal',
        ),
        migrations.AddField(
            model_name='careergoal',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='bullets',
            field=models.ManyToManyField(to='resume.Line'),
        ),
    ]
