# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20160228_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careergoal',
            options={'ordering': ['sorting_value']},
        ),
        migrations.AddField(
            model_name='careergoal',
            name='sorting_value',
            field=models.IntegerField(default=1),
        ),
    ]
