# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20160228_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_value', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(blank=True, to='resume.ResumeCategory')),
                ('lines', models.ManyToManyField(to='resume.Line')),
            ],
            options={
                'ordering': ['sorting_value'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericListSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting_value', models.IntegerField(default=1)),
                ('section_title', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(blank=True, to='resume.ResumeCategory')),
            ],
            options={
                'ordering': ['sorting_value'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='font',
            field=models.CharField(choices=[(b'Lato-Thin, Lato-ThinItalic, Arial, sans-serif;', b'Lato-Thin'), (b'Helvetica, Arial, sans-serif;', b'Helvetica'), (b'Georgia, Arial, sans-serif', b'Georgia')], default=b'Lato-Thin, Lato-ThinItalic, Arial, sans-serif;', max_length=255),
        ),
        migrations.AddField(
            model_name='genericlistsection',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='genericlistitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.GenericListSection'),
        ),
    ]
