# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20160515_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='section_order',
            field=models.TextField(default=resume.models.get_sections),
        ),
        migrations.AlterField(
            model_name='genericlistsection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='generic_list_section', to='resume.ResumeCategory'),
        ),
    ]
