# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20160522_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careergoal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genericlistsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='programmingskills',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={},
        ),
        migrations.RemoveField(
            model_name='genericlistsection',
            name='section_title',
        ),
        migrations.AddField(
            model_name='careergoal',
            name='_section_title',
            field=models.CharField(blank=True, help_text='Displays at top of section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='_section_title',
            field=models.CharField(blank=True, help_text='Displays at top of section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genericlistsection',
            name='_section_title',
            field=models.CharField(blank=True, help_text='Displays at top of section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programmingskills',
            name='_section_title',
            field=models.CharField(blank=True, help_text='Displays at top of section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='_section_title',
            field=models.CharField(blank=True, help_text='Displays at top of section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='genericlistsection',
            name='categories',
            field=models.ManyToManyField(blank=True, to='resume.ResumeCategory'),
        ),
        migrations.AlterField(
            model_name='genericlistsection',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='programmingskills',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
